name: RELEASE

on:
  - push
  - pull_request

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 8

      - name: run linter
        run: eslint . --ext .js,.jsx,.ts,.tsx

      - name: build
        run: pnpm build

      - name: publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: pnpm publish

